spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: 32fff58c-05d9-4790-8c68-011881d8175a
        credential:
          client-id: 076c4363-7f4a-4205-8eaa-8d45e429fb3b
          client-secret: DUh8Q~d0vdMc82dh665VzUhg3UJ3N16pSjSGTbf4
  application:
    name: azure-service

server:
  port: 8085
  forward-headers-strategy: native

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka
    instance:
    preferIpAddress: true



#okta :
#  oauth2 :
#    clientId : 0oaaqutdyvaLPKDkq5d7
#    clientSecret : Xyq8ISLzXF-w9HPLWicPLma4j8BL_P-ObiK74L16oCh1OiL9dllS-fOvRs1Kah3U
#    issuer : https://dev-02015639.okta.com/oauth2/default
#    redirect_uri : /login/oauth2/code/okta
